BASE: ../Base-DETR.yaml
MODEL:
  RESNETS:
    WEIGHTS: pretrained_weight/LResNet50IR_CASIA/epoch_25.pth
  TRANSFORMERS:
    NUM_QUERIES: 64
    QUERIES_WEIGHT: feature_dictionary/CASIA/100000/dictionary_second_64.pickle
    HIDDEN_DIM: 256
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  BASE_LR: 0.0001
  TRAIN_BACKBONE: False
  BATCH_SIZE: 64
  MOMENTUM: 0.9
  NUM_EPOCHS: 30
  STEP_FACTOR: 0.3
  STEP_SIZE: 10
  WEIGHT_DECAY: 0.0005
SAVE: results