BASE: ../Base-DETR.yaml
MODEL:
  RESNETS:
    WEIGHTS: pretrained_weight/LResNet50IR_CASIA/epoch_25.pth
  TRANSFORMERS:
    NUM_ENCODER_LAYERS: 0
    NUM_DECODER_LAYERS: 6
    NUM_QUERIES: 64
    HIDDEN_DIM: 256
  SCALING: 30.0
  MARGIN: 0.4
  GLOBAL_FC: False
  FEATURE_MAPS: second
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  BASE_LR: 0.0001
  TRAIN_BACKBONE: False
  CLIP_GRAD: True
  BATCH_SIZE: 64
  MOMENTUM: 0.9
  NUM_EPOCHS: 20
  STEP_FACTOR: 0.5
  STEP_SIZE: 15
  WEIGHT_DECAY: 0.0001
SAVE: results