BASE: ../Base-VGG_Attn_Prototype.yaml
MODEL:
  WEIGHTS: ""
  VGG:
    WEIGHTS: pretrained_weight/VGG_MNIST/epoch_10.pt
  ATTN:
    NUM_CLUSTERS: 512
    WEIGHTS: feature_dictionary/MNIST/dictionary_vgg_pool4_512_ori.pickle
    PERCENT_U: 0.2
    PERCENT_L: 0.8
  PROTOTYPE:
    WEIGHTS: prototype_weight/prototype_10_4_MNIST.pkl
    NUM_PROTOTYPES: 4
    METHOD: kmeans
  NUM_CLASSES: 10
  NORM_ATTN: True
  USE_THRESH: True
  NORM_BEFORE_ATTN: True
  RECURRENT_STEP: 1
DATASETS:
  TRAIN: mnist_train
  VAL: mnist_test
  TEST: mnist_test_occ_black
SOLVER:
  NUM_EPOCHS: 20
  BATCH_SIZE: 32
  BASE_LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  STEP_SIZE: 5
  STEP_FACTOR: 0.5
  VC_LAMBDA: 1.0
  P_LAMBDA: 1.0
SAVE: results