BASE: ../Base-VGG.yaml
MODEL:
  WEIGHTS: ""
DATASETS:
  TRAIN: mnist_train
  VAL: mnist_test
  TEST: mnist_test_occ
SOLVER:
  NUM_EPOCHS: 30
  BATCH_SIZE: 32
  BASE_LR: 0.005
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  STEP_SIZE: 5
  STEP_FACTOR: 0.5
SAVE: results