MODEL:
  NAME: vgg_attn_proto
  VGG:
    LAYERS: [2, 2, 3, 3, 3]
    FILTER: [64, 128, 256, 512, 512]
  ATTN:
    NUM_CLUSTERS: 64
    PERCENT_U: 0.2
    PERCENT_L: 0.8
  PROTOTYPE:
    NUM_PROTOTYPES: 4
    METHOD: kmeans
  NUM_CLASSES: 10
  NORM_ATTN: True
  USE_THRESH: True
  NORM_BEFORE_ATTN: True
  RECURRENT_STEP: 1
DATASETS:
  TRAIN: mnist_train
  VAL: mnist_test
  TEST: ""
SOLVER:
  NUM_EPOCHS: 30
  BATCH_SIZE: 32
  BASE_LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  STEP_SIZE: 5
  STEP_FACTOR: 0.5
  VC_LAMBDA: 1.0
  P_LAMBDA: 1.0