MODEL:
  NAME: resnet
  RESNETS:
    LAYERS: [3, 4, 14, 3]
    FILTER: [64, 64, 128, 256, 512]
  OUT_FEATURES: 512
  NUM_CLASSES: 10575
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  NUM_EPOCHS: 30
  BATCH_SIZE: 64
  BASE_LR: 0.0001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  STEP_SIZE: 5
  STEP_FACTOR: 0.5
  VC_LAMBDA: 1.0