MODEL:
  NAME: detr
  RESNETS:
    LAYERS: [3, 4, 14, 3]
    FILTER: [64, 64, 128, 256, 512]
  TRANSFORMERS:
    NUM_ENCODER_LAYERS: 6
    NUM_DECODER_LAYERS: 6 
    NUM_HEADS: 8
    NUM_QUERIES: 64
    HIDDEN_DIM: 256
    POSITION_EMBEDDING: sine
    INTERMEDIATE_RESULTS: True
  OUT_FEATURES: 512
  NUM_CLASSES: 10575
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  NUM_EPOCHS: 20
  BATCH_SIZE: 16
  BASE_LR: 0.0001
  BACKBONE_LR: 0.00001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  STEP_SIZE: 8
  STEP_FACTOR: 0.5