BASE: ../Base-LResNet50IR.yaml
MODEL:
  WEIGHTS: ""
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  BASE_LR: 0.01
  BATCH_SIZE: 16
  MOMENTUM: 0.9
  NUM_EPOCHS: 30
  STEP_FACTOR: 0.5
  STEP_SIZE: 5
  WEIGHT_DECAY: 0.0005
SAVE: results