BASE: ../Base-LResNet50IR.yaml
MODEL:
  WEIGHTS: ""
  SCALING: 30.0
  MARGIN: 0.4
DATASETS:
  TRAIN: [casia]
  VAL: [lfw]
  TEST: [lfw_masked]
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE: 16
  MOMENTUM: 0.9
  NUM_EPOCHS: 35
  STEP_FACTOR: 0.1
  STEP_SIZE: 25
  WEIGHT_DECAY: 0.0001
SAVE: results